-- +goose Up
-- +goose StatementBegin
CREATE TABLE states (
    id INTEGER UNIQUE,
    name_en TEXT NOT NULL,
    name_ru TEXT NOT NULL,
    country_id INTEGER NOT NULL,
    FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE CASCADE
            ON UPDATE CASCADE
);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (7, 'Minsk', 'Минская', 1);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (8, 'CA', 'Калифорния', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (9, 'OR', 'Орегон', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (10, 'Ternopil', 'Тернопольская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (11, 'Сhernivtsi', 'Черновицкая', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (12, 'WA', 'Вашингтон', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (13, 'MA', 'Массачусетс', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (14, 'Zaporizhzhia', 'Запорожская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (15, 'GA', 'Джорджия', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (16, 'Rivne', 'Ровенская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (17, 'Kyiv', 'Киевская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (18, 'Vinnytsia', 'Винницкая', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (19, 'Ivano-Frankivsk', 'Ивано-Франковская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (20, 'NY', 'Нью-Йорк', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (21, 'VA', 'Вирджиния', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (22, 'OH', 'Огайо', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (23, 'FL', 'Флорида', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (24, 'Donetsk', 'Донецкая', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (25, 'Ida-Virumaa', 'Ида-Вирумаа', 59);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (26, 'Vilnius', 'Вильнюс', 62);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (27, 'Cherkasy', 'Черкасская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (28, 'Odessa', 'Одесская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (29, 'Baden-Württemberg', 'Баден-Вюртемберг', 70);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (30, 'Brest', 'Брестская', 1);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (31, 'PA', 'Пенсильвания', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (32, 'MN', 'Миннесота', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (33, 'ON', 'Онтарио', 89);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (34, 'West', 'Восточная', 94);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (35, 'Tula', 'Тульская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (36, 'Moscow', 'Московская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (37, 'Dnipropetrovsk', 'Днепропетровская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (38, 'Chisinau', 'Кишинев', 110);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (39, 'Samarskaya', 'Самарская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (40, 'Vidzeme', 'Виидземе', 116);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (41, 'Mykolaivska', 'Николаевская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (42, 'NC', 'Северная Каролина', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (43, 'Lviv', 'Львовская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (44, 'IL', 'Иллинойс', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (45, 'Balti municipality', 'Бельцы муниципий', 110);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (46, 'Nizhny Novgorod', 'Нижегородская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (47, 'Leningrad', 'Ленинградская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (48, 'Pskov', 'Псковская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (49, 'Permskiy', 'Пермский', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (50, 'Rostov', 'Ростовская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (51, 'Krasnodarskiy', 'Краснодарский', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (52, 'Uusimaa', 'Уусимаа', 151);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (53, 'Gomel', 'Гомельская', 1);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (54, 'Novosibirsk', 'Новосибирская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (55, 'Chelyabinskaya', 'Челябинская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (56, 'Krasnoyarskiy', 'Красноярский', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (57, 'Altayskiy', 'Алтайский', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (58, 'Tomskaya', 'Томская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (59, 'Volynska', 'Волынская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (60, 'Omskaya', 'Омская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (61, 'Ulyanovskaya', 'Ульяновская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (62, 'Tatarstan', 'Татарстан', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (63, 'Sverdlovskaya', 'Свердловская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (64, 'Yaroslavskaya', 'Ярославская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (65, 'Tverskaya', 'Тверская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (66, 'Tyva', 'Тыва', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (67, 'Kemerovskaya', 'Кемеровская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (68, 'Chernihivska', 'Черниговская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (69, 'Crimea', 'Крым', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (70, 'Greater London', 'Большой Лондон', 152);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (71, 'North Rhine-Westphalia', 'Северный Рейн-Вестфалия', 70);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (72, 'Mogilev', 'Могилевская', 1);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (73, 'Tambov', 'Тамбовская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (74, 'Zhytomyr', 'Житомирская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (75, 'Columbia', 'Колумбия', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (76, 'Madrid', 'Мадрид', 153);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (77, 'Kharkiv', 'Харьковская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (78, 'South Carolina', 'Южная Каролина', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (79, 'Kherson', 'Херсонская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (80, 'Tennessee', 'Теннесси', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (81, 'Colorado', 'Колорадо', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (82, 'Belgorod', 'Белгородская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (83, 'Khabarovskiy', 'Хабаровский', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (84, 'Khmelnytskyi', 'Хмельницкая', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (85, 'Almaty', 'Алматинская', 154);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (86, 'Mazowieckie', 'Мазовецкое', 155);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (87, 'Zakarpatskaya', 'Закарпатская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (88, 'Idaho', 'Айдахо', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (89, 'Udmurt', 'Удмуртия', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (90, 'Ceadîr-Lunga', 'Чадыр-Лунга', 110);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (91, 'Alaska', 'Аляска', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (92, 'New Jersey', 'Нью-Джерси', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (93, 'Poltava', 'Полтавская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (94, 'Berlin', 'Берлин', 70);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (95, 'Irkutsk', 'Иркутская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (96, 'Penza', 'Пенза', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (97, 'Karaganda', 'Карагандинская', 154);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (98, 'Volgograd', 'Волгоградская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (99, 'Kabardino-Balkarian', 'Кабардино-Балкарская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (100, 'Vitebsk', 'Витебская', 1);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (101, 'Vladimir', 'Владимирская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (102, 'Kursk', 'Курская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (103, 'Kirovohrad', 'Кировоградская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (104, 'Sumy', 'Сумская', 12);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (105, 'Bryansk', 'Брянская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (106, 'Bashkortostan', 'Башкортостан', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (107, 'Central Bohemian', 'Среднечешский', 156);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (108, 'NE', 'Небраска', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (109, 'MO', 'Миссури', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (110, 'Prague', 'Прага', 156);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (111, 'Chuy', 'Чуйская', 157);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (112, 'Iowa', 'Айова', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (113, 'OK', 'Оклахома', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (114, 'Transnistria', 'Приднестровье', 110);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (115, 'Voronezh', 'Воронежская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (116, 'Brussels-Capital', 'Брюссельский столичный', 158);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (117, 'Kentucky', 'Кентукки', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (118, 'Grodno', 'Гродненская', 1);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (119, 'East Kazakhstan', 'Восточно-Казахстанская', 154);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (120, 'Smolensk', 'Смоленская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (121, 'Basque Country', 'Страна Басков', 153);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (122, 'Montana', 'Монтана', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (123, 'Catalonia', 'Каталония', 153);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (124, 'New South Wales', 'Новый Южный Уэльс', 159);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (125, 'Indiana', 'Индиана', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (126, 'QC', 'Квебек', 89);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (127, 'TX', 'Техас', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (128, 'Komi', 'Коми', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (129, 'Tashkent', 'Ташкент', 160);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (130, 'Lipetsk', 'Липецк', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (131, 'Kaluga', 'Калужская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (132, 'Amur', 'Амурская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (133, 'Maryland', 'Мэриленд', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (134, 'Karelia', 'Карелия', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (135, 'Jambyl', 'Жамбылская', 154);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (136, 'Queensland', 'Квинсленд', 159);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (137, 'MI', 'Мичиган', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (138, 'Kaliningrad', 'Калининградская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (139, 'Novgorod', 'Новгородская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (140, 'AZ', 'Аризона', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (141, 'Valencia', 'Валенсия', 153);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (142, 'Alberta', 'Альберта', 89);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (143, 'Adygeya', 'Адыгея', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (144, 'Baki', 'Баку', 161);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (145, 'Sakha', 'Саха', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (146, 'South Australia', 'Южная Австралия', 159);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (147, 'Kuyavian-Pomeranian', 'Куявско-Поморское', 155);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (148, 'Orenburg', 'Оренбургская', 9);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (149, 'SD', 'Южная Дакота', 4);
INSERT INTO `states` (`id`, `name_en`, `name_ru`, `country_id`) VALUES (150, 'Bavaria', 'Бавария', 70);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS states;
-- +goose StatementEnd
