-- +goose Up
-- +goose StatementBegin
CREATE TABLE cities (
    id INTEGER UNIQUE,
    name_en TEXT NOT NULL,
    name_ru TEXT NOT NULL,
    state_id INTEGER NOT NULL,
    FOREIGN KEY (state_id) REFERENCES states(id) ON DELETE CASCADE
            ON UPDATE CASCADE
);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (7, 'Minsk', 'Минск', 7);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (8, 'Sacramento', 'Сакраменто', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (9, 'Portland', 'Портленд', 9);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (10, 'Ternopil', 'Тернополь', 10);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (11, 'Сhernivtsi', 'Черновцы', 11);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (12, 'Vancouver', 'Ванкувер', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (13, 'Chicopee', 'Чикопи', 13);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (14, 'Zaporizhzhia', 'Запорожье', 14);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (15, 'Snellville', 'Снеллвилль', 15);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (16, 'Kent', 'Кент', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (17, 'Marysville', 'Мэрисвилль', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (18, 'Varash', 'Вараш', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (19, 'Mukilteo', 'Мукилтео', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (20, 'Takoma', 'Такома', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (21, 'Fairview', 'Фэрвью', 9);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (22, 'Seattle', 'Сиэтл', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (23, 'Kyiv', 'Киев', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (24, 'Sofievska Borshchagovka', 'Софиевская Борщаговка', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (25, 'Nedoboivtsy', 'Недобоевцы', 11);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (26, 'Rivne', 'Ровно', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (27, 'Vinnytsia', 'Винница', 18);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (28, 'Ivano-Frankivsk', 'Ивано-Франковск', 19);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (29, 'Edgewood', 'Эджвуд', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (30, 'Rochester', 'Рочестер', 20);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (31, 'Fairfax', 'Фэйрфакс', 21);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (32, 'Federal Way', 'Федерал Уей', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (33, 'Columbus', 'Колумбус', 22);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (34, 'West Springfield', 'Вест-Спрингфилд', 13);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (35, 'Westfield', 'Уэстфилд', 13);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (36, 'Jacksonville', 'Джексонвилл', 23);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (37, 'Broadview Heights', 'Бродвью Хайтс', 22);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (38, 'Spokane', 'Спокан', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (39, '​Auburn', 'Оборн', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (40, 'Mariupol', 'Мариуполь', 24);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (41, 'Narva', 'Нарва', 25);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (42, 'Vilnius', 'Вильнюс', 26);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (43, 'Cherkasy', 'Черкассы', 27);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (44, 'Odessa', 'Одесса', 28);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (45, 'Battle Ground', 'Батл Граунд', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (46, 'Lahr/Schwarzwald', 'Лар (Шварцвальд)', 29);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (47, 'Baranovichi', 'Барановичи', 30);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (48, 'Brest', 'Брест', 30);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (49, 'Des Moines', 'Де-Мойн', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (50, 'Belgorod-Dnestrovsky', 'Белгород-Днестровский', 28);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (51, 'Roseville', 'Розвилл', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (52, 'Syracuse', 'Сиракьюс', 20);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (53, 'Camillus', 'Камилус', 20);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (54, 'Binghamton', 'Бингемтон', 20);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (55, 'Utica', 'Ютика', 20);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (56, 'Buffalo', 'Буффало', 20);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (57, 'Erie', 'Эри', 31);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (58, 'Atlanta', 'Атланта', 15);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (59, 'Shakopee', 'Шакопи', 32);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (60, 'London', 'Лондон', 33);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (61, 'Everett', 'Эверетт', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (62, 'Mount Vernon', 'Маунт-Вернон', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (63, 'Arad', 'Арад', 34);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (64, 'Zaoksky', 'Заокский', 35);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (65, 'Moscow', 'Москва', 36);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (66, 'Irpen', 'Ирпень', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (67, 'Brooklyn Park', 'Бруклин-Парк', 32);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (68, 'Kryvyi Rih', 'Кривой Рог', 37);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (69, 'Nikopol', 'Никополь', 37);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (70, 'Vyshneve', 'Вишневое', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (71, 'Granite Bay', 'Гранит Бэй', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (72, 'Dnipro', 'Днепр', 37);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (73, 'Harrisburg', 'Гаррисберг', 31);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (74, 'Chisinau', 'Кишинев', 38);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (75, 'Tolyatti', 'Тольятти', 39);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (76, 'Kostiantynivka', 'Константиновка', 24);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (77, 'Rīga', 'Рига', 40);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (78, 'Mykolaiv', 'Николаев', 41);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (79, 'Zheleznodorozhnyy', 'Железнодорожный', 36);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (80, 'Asheville', 'Ашвилл', 42);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (81, 'Lviv', 'Львов', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (82, 'Zolochiv', 'Золочев', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (83, 'Chicago', 'Чикаго', 44);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (84, 'Otyniya', 'Отыния', 19);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (85, 'Fryazino', 'Фрязино', 36);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (86, 'Sea Cliff', 'Си Клифф', 20);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (87, 'Podolsk', 'Подольск', 36);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (88, 'Solonka', 'Солонка', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (89, 'Balti', 'Бельцы', 45);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (90, 'Nizhnij Novgorod', 'Нижний Новгород', 46);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (91, 'Plymouth', 'Плимут', 32);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (92, 'Park Ridge', 'Парк-Ридж', 44);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (93, 'Bellevue', 'Белвью', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (94, 'Sankt-Peterburg', 'Санкт-Петербург', 47);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (95, 'Glendale', 'Глендейл', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (96, 'Pskov', 'Псков', 48);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (97, 'Melitopol', 'Мелитополь', 14);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (98, 'Perm', 'Перьм', 49);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (99, 'Rostov-na-Donu', 'Ростов-на-Дону', 50);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (100, 'Renton', 'Рентон', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (101, 'Khartsyzk', 'Харцызск', 24);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (102, 'Novi Obikhody', 'Новые Обиходы', 18);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (103, 'Krasnodar', 'Краснодар', 51);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (104, 'Slovyansk', 'Славянск', 24);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (105, 'Helsinki', 'Хельсинки', 52);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (106, 'Gomel', 'Гомель', 53);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (107, 'Novosibirsk', 'Новосибирск', 54);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (108, 'Chelyabinsk', 'Челябинск', 55);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (109, 'Achinsk', 'Ачинск', 56);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (110, 'Barnaul', 'Барнаул', 57);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (111, 'Shitamova', 'Штамово', 58);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (112, 'Hemet', 'Хемет', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (113, 'Boryslav', 'Борислав', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (114, 'Zdolbuniv', 'Здолбунов', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (115, 'Lutsk', 'Луцк', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (116, 'Samara', 'Самара', 39);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (117, 'Omsk', 'Омск', 60);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (118, 'Ulyanovsk', 'Ульяновск', 61);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (119, 'Kazan', 'Казань', 62);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (120, 'Nizhny Tagil', 'Нижний Тагил', 63);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (121, 'Yaroslavl', 'Ярославль', 64);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (122, 'Miass', 'Миасс', 55);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (123, 'Tver', 'Тверь', 65);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (124, 'Kyzyl', 'Кызыл', 66);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (125, 'Kemerovo', 'Кемерово', 67);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (126, 'Krasnoyarsk', 'Красноярск', 56);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (127, 'Chernihiv', 'Чернигов', 68);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (128, 'Sevastopol', 'Севастополь', 69);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (129, 'Timofeyevka', 'Тимофеевка', 39);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (130, 'London', 'Лондон', 70);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (131, 'Oregon', 'Орегон', 9);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (132, 'Mytishchi', 'Мытищи', 36);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (133, 'Kenmore', 'Кенмор', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (134, 'Svyatohirsk', 'Святогорск', 24);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (135, 'Bothell', 'Ботелл', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (136, 'Agawam', 'Агауэм', 13);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (137, 'Milwaukie', 'Милуоки', 9);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (138, 'Donetsk', 'Донецк', 24);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (139, 'North Port', 'Норт-Порт', 23);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (140, 'Parma', 'Парма', 22);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (141, 'Kostopil', 'Костополь', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (142, 'Minden', 'Минден', 71);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (143, 'Berezhany', 'Бережаны', 10);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (144, 'Yekaterinburg', 'Екатеринбург', 63);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (145, 'Kvasyliv', 'Квасилов', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (146, 'Babrujsk', 'Бобруйск', 72);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (147, 'Pargolovo', 'Парголово', 47);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (148, 'Mount Crawford', 'Моунт Крафорд', 21);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (149, 'Tambov', 'Тамбов', 73);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (150, 'Bili Oslavy', 'Белые Ославы', 19);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (151, 'Irvine', 'Ирвайн', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (152, 'Brody', 'Броды', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (153, 'Zhytomyr', 'Житомир', 74);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (154, 'Boring', 'Боринг', 9);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (155, 'Washington', 'Вашингтон', 75);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (156, 'West Sacramento', 'Запад Сакраменто', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (157, 'Makiivka', 'Макеевка', 24);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (158, 'Kobryn', 'Кобрин', 30);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (159, 'Laguna Hills', 'Лагуна-Хиллз', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (160, 'Madrid', 'Мадрид', 76);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (161, 'Kharkiv', 'Харьков', 77);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (162, 'Inman', 'Инман', 78);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (163, 'Ephrata', 'Эфрата', 31);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (164, 'State College', 'Стэйт Колледж', 31);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (165, 'Kherson', 'Херсон', 79);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (166, 'Nova Kakhovka', 'Новая Каховка', 79);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (167, 'Chattanooga', 'Чаттануга', 80);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (168, 'Uman', 'Умань', 27);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (169, 'Bensenville', 'Бенсенвилл', 44);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (170, 'Cortland', 'Кортленд', 20);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (171, 'Arvada', 'Арвада', 81);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (172, 'St. Louis Park', 'Сент-Луис-Парк', 32);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (173, 'Minneapolis', 'Миннеаполис', 32);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (174, 'Stary Oskol', 'Старый Оскол', 82);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (175, 'Khabarovsk', 'Хабаровск', 83);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (176, 'Khmelnytskyi', 'Хмельницкий', 84);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (177, 'Katyuzhanka', 'Катюжанка', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (178, 'Feasterville-Trevose', 'Феастервилл-Тревос', 31);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (179, 'Marhanets', 'Марганец', 37);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (180, 'Sterling', 'Стерлинг', 21);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (181, 'Manevichi', 'Маневичи', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (182, 'Berdychiv', 'Бердичев', 74);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (183, 'Hartville', 'Хартвилл', 22);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (184, 'Pliescanicy', 'Плещеницы', 7);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (185, 'Aurora', 'Орора', 81);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (186, 'Almaty', 'Алматы', 85);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (187, 'Toronto', 'Торонто', 33);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (188, 'Dniprorudne', 'Днепрорудное', 14);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (189, 'Warszawa', 'Варшава', 86);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (190, 'Uzhhorod', 'Ужгород', 87);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (191, 'Kriukivshchyna', 'Крюковщина', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (192, 'Meridian', 'Меридиан', 88);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (193, 'Boise', 'Бойсе', 88);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (194, 'Izhevsk', 'Ижевск', 89);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (195, 'Remeniv', 'Ременов', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (196, 'Ceadîr-Lunga', 'Чадыр-Лунга', 90);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (197, 'Yuzhne', 'Южный', 28);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (198, 'Ham Lake', 'Хам-Лейк', 32);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (199, 'Ivangorod', 'Ивангород', 47);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (200, 'Pochaiv', 'Почаев', 10);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (201, 'Krasnokamsk', 'Краснокамск', 49);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (202, 'Novoiavorivsk', 'Новояворовск', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (203, 'Pasco', 'Паско', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (204, 'Vasylkiv', 'Васильков', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (205, 'Suwanee', 'Савани', 15);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (206, 'Bila Tserkva', 'Белая Церковь', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (207, 'Fairless Hills', 'Фэрлесс Хилс', 31);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (208, 'Levittown', 'Левитаун', 31);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (209, 'Khryplyn', 'Хриплин', 19);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (210, 'Wasilla', 'Уасилла', 91);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (211, 'Delaware', 'Делавэр', 31);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (212, 'Vineland', 'Вайнленд', 92);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (213, 'Spartanburg', 'Спартанберг', 78);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (214, 'Anderson', 'Андерсон', 78);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (215, 'Kremenchuk', 'Кременчуг', 93);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (216, 'Kovel', 'Ковель', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (217, 'Berlin', 'Берлин', 94);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (218, 'Chervonohrad', 'Червоноград', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (219, 'Usolye-Sibirskoye', 'Усолье-Сибирское', 95);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (220, 'Detmold', 'Детмольд', 71);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (221, 'Penza', 'Пенза', 96);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (222, 'Maple Falls', 'Мейпл Фолс', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (223, 'Naberezhnye Chelny', 'Набережные Челны', 62);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (224, 'Tomsk', 'Томск', 58);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (225, 'Pereyaslav-Khmelnytskyi', 'Переяслав-Хмельницкий', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (226, 'Dmytrivka', 'Дмитровка', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (227, 'Medina', 'Медина', 88);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (228, 'Odintsovo', 'Одинцово', 36);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (229, 'Happy Valley', 'Хаппи Вэлли', 9);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (230, 'Novovolynsk', 'Нововолынск', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (231, 'Velikiye Luki', 'Великие Луки', 48);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (232, 'Woodstock', 'Вудсток', 15);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (233, 'Citrus Heights', 'Ситрес Хайтс', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (234, 'Barysaw', 'Борисов', 7);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (235, 'Vyshnivets', 'Вишневец', 10);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (236, 'Kamianets-Podilskyi', 'Каменец-Подольский', 84);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (237, 'Horishni Sherivtsi', 'Горишние Шеровцы', 11);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (238, 'Kolomyia', 'Коломыя', 19);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (239, 'Salem', 'Сейлем', 9);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (240, 'Bratske', 'Братское', 14);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (241, 'Kramatorsk', 'Краматорск', 24);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (242, 'Saran', 'Сарань', 97);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (243, 'Repuzhyntsi', 'Репужинцы', 11);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (244, 'Olshany', 'Ольшаны', 30);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (245, 'Kivertsi', 'Киверцы', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (246, 'Leicester', 'Лестер', 42);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (247, 'Poltava', 'Полтава', 93);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (248, 'Charlotte', 'Шарлотт', 42);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (249, 'Volgograd', 'Волгоград', 98);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (250, 'Maysky', 'Майский', 99);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (251, 'York', 'Йорк', 31);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (252, 'Oleksandriya', 'Александрия', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (253, 'Lyshche', 'Лыще', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (254, 'Orsha', 'Орша', 100);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (255, 'Mankovichi', 'Маньковичи', 100);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (256, 'Boyarka', 'Боярка', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (257, 'Ostroh', 'Острог', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (258, 'Prokhladny', 'Прохладный', 99);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (259, 'Torchyn', 'Торчин', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (260, 'Stepan', 'Степань', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (261, 'Vladimir', 'Владимир', 101);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (262, 'Tarpon Springs', 'Тарпон Спрингс', 23);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (263, 'Pinsk', 'Пинск', 30);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (264, 'Smila', 'Смела', 27);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (265, 'Zhovti Vody', 'Жёлтые Воды', 37);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (266, 'Kursk', 'Курск', 102);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (267, 'Sarny', 'Сарны', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (268, 'Serpukhov', 'Серпухов', 36);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (269, 'Svitlovodsk', 'Светловодск', 103);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (270, 'Sochi', 'Сочи', 51);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (271, 'Huntingdon Valley', 'Хантингдон Вэлли', 31);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (272, 'Slobozhanske', 'Слобожанское', 37);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (273, 'Kamianske', 'Каменское', 37);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (274, 'Achairskiy', 'Ачаирский', 60);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (275, 'Khust', 'Хуст', 87);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (276, 'Shostka', 'Шостка', 104);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (277, 'Kropyvnytskyi', 'Кропивницкий', 103);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (278, 'Dubliany', 'Дубляны', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (279, 'Brovary', 'Бровары', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (280, 'Buzivka', 'Бузовка', 27);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (281, 'Kamyanka', 'Каменка', 11);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (282, 'Tarasivka', 'Тарасовка', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (283, 'Bryansk', 'Брянск', 105);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (284, 'Ivanava', 'Иваново', 30);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (285, 'Ufa', 'Уфа', 106);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (286, 'Prague', 'Прага', 107);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (287, 'Lincoln', 'Линкольн', 108);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (288, 'Kotiv', 'Котов', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (289, 'Uzyn', 'Узин', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (290, 'Sedalia', 'Седалия', 109);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (291, 'Prague', 'Прага', 110);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (292, 'Bishkek', 'Бишкек', 111);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (293, 'Komsomolsk-on-Amur', 'Комсомольск-на-Амуре', 83);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (294, 'Indianola', 'Индианола', 112);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (295, 'Matthews', 'Мэтьюз', 42);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (296, 'Tulsa', 'Талса', 113);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (297, 'Mlyniv', 'Млинов', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (298, 'Dubno', 'Дубно', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (299, 'Viciebsk', 'Витебск', 100);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (300, 'Mukachevo', 'Мукачево', 87);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (301, 'Lititz', 'Литиц', 31);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (302, 'Barauliany', 'Боровляны', 7);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (303, 'Perebykivtsi', 'Перебыковцы', 11);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (304, 'Cleveland', 'Кливленд', 22);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (305, 'Lubny', 'Лубны', 93);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (306, 'Victorville', 'Викторвилл', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (307, 'Novohrad-Volynskyi', 'Новоград-Волынский', 74);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (308, 'Tokmak', 'Токмак', 14);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (309, 'Bucha', 'Буча', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (310, 'Priozersk', 'Приозерск', 47);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (311, 'Vyzhnytsya', 'Вижница', 11);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (312, 'Rio Linda', 'Рио Линда', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (313, 'Bendery', 'Бендеры', 114);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (314, 'Biaroza', 'Береза', 30);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (315, 'Volodymyr-Volynskyi', 'Владимир-Волынский', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (316, 'Apostolove', 'Апостолово', 37);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (317, 'Volodymyrets', 'Владимирец', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (318, 'Mohyliv-Podilskyi', 'Могилев-Подольский', 18);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (319, 'Port Republic', 'Порт Репаблик', 21);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (320, 'Enerhodar', 'Энергодар', 14);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (321, 'Izmail', 'Измаил', 28);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (322, 'Blahovishchenka', 'Благовещенка', 37);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (323, 'Somovo', 'Сомово', 115);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (324, 'Sumy', 'Сумы', 104);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (325, 'Derhachi', 'Дергачи', 77);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (326, 'Nampa', 'Нампа', 88);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (327, 'Roznychi', 'Розничи', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (328, 'Nizhyn', 'Нежин', 68);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (329, 'Rozhyshche', 'Рожище', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (330, 'Chornomorsk', 'Черноморск', 28);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (331, 'Koln', 'Кёльн', 71);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (332, 'Zdovbytsia', 'Здолбица', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (333, 'Dunaivtsi', 'Дунаевцы', 84);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (334, 'Dymer', 'Дымер', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (335, 'Mogilev', 'Могилёв', 72);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (336, 'Zolotonosha', 'Золотоноша', 27);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (337, 'Kurganinsk', 'Курганинск', 51);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (338, 'Volgodonsk', 'Волгодонск', 50);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (339, 'Kolodishchi', 'Колодищи', 7);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (340, 'Zarvantsi', 'Зарванцы', 18);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (341, 'Philadelphia', 'Филадельфия', 31);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (342, 'Bruxelles', 'Брюссель', 116);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (343, 'Nicholasville', 'Николасвилл', 117);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (344, 'Pidhaitsi', 'Подгайцы', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (345, 'Yeysk', 'Ейск', 51);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (346, 'Vawkavysk', 'Волковыск', 118);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (347, 'Velyke Verbche', 'Великое Вербче', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (348, 'Ust-Kamenogorsk', 'Усть-Каменогорск', 119);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (349, 'Bellingham', 'Беллингхем', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (350, 'Truskavets', 'Трускавец', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (351, 'Istra', 'Истра', 36);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (352, 'Khimki', 'Химки', 36);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (353, 'Yartsevo', 'Ярцево', 120);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (354, 'San-Sebastian', 'Сан-Себастьян', 121);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (355, 'Grodno', 'Гродно', 118);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (356, 'Missoula', 'Мизула', 122);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (357, 'Pervomaisk', 'Первомайск', 41);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (358, 'Myrhorod', 'Миргород', 93);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (359, 'Horokhiv', 'Горохов', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (360, 'Suprunivka', 'Супруновка', 93);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (361, 'Barcelona', 'Барселона', 123);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (362, 'Sydney', 'Сидней', 124);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (363, 'Rancho Cordova', 'Ранчо Кордова', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (364, 'Montebello', 'Монтебелло', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (365, 'Rovantsi', 'Рованцы', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (366, 'Slutsk', 'Слуцк', 7);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (367, 'Radyvyliv', 'Радивилов', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (368, 'Motovylivka', 'Мотовиловка', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (369, 'Volochysk', 'Волочиск', 84);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (370, 'Nizhnekamsk', 'Нижнекамск', 62);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (371, 'Kamin-Kashyrskyi', 'Камень-Каширский', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (372, 'Pohreby', 'Погребы', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (373, 'Michurinsk', 'Мичуринск', 73);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (374, 'Kalush', 'Калуш', 19);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (375, 'Lebedyn', 'Лебедин', 104);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (376, 'Chegdomyn', 'Чегдомын', 83);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (377, 'Elkhart', 'Элкхарт', 125);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (378, 'New York', 'Нью-Йорк', 20);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (379, 'Orlando', 'Орландо', 23);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (380, 'Klesiv', 'Клесов', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (381, 'Bohuslav', 'Богуслав', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (382, 'Zboriv', 'Зборов', 10);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (383, 'Minusinsk', 'Минусинск', 56);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (384, 'Raymond', 'Реймонд', 108);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (385, 'Pavlohrad', 'Павлоград', 37);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (386, 'Ternivka', 'Терновка', 37);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (387, 'Stryi', 'Стрый', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (388, 'Montreal', 'Монреаль', 126);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (389, 'Voronezh', 'Воронеж', 115);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (390, 'New Braunfels', 'Нью Браунфельс', 127);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (391, 'Syktyvkar', 'Сыктывкар', 128);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (392, 'Knoxville', 'Ноксвилл', 80);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (393, 'Tashkent', 'Ташкент', 129);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (394, 'St. Petersburg', 'Сент-Питерсберг', 23);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (395, 'Lipetsk', 'Липецк', 130);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (396, 'Niagara Falls', 'Ниагара-Фолс', 33);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (397, 'Kremenets', 'Кременец', 10);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (398, 'Rafalivka', 'Рафаловка', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (399, 'Novoivanovskoye', 'Новоивановское', 36);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (400, 'Maiaky', 'Маяки', 28);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (401, 'Lokachi', 'Локачи', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (402, 'Busk', 'Буск', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (403, 'Rudnya', 'Рудня', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (404, 'Velyka Omeliana', 'Великая Омеляна', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (405, 'Krasnoperekopsk', 'Красноперекопск', 69);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (406, 'Obninsk', 'Обнинск', 131);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (407, 'Escondido', 'Эскондидо', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (408, 'Damascus', 'Дамаскус', 9);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (409, 'Anaheim', 'Анахайм', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (410, "Rava-Rus\'ka", 'Рава-Русская', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (411, 'Glen Ellyn', 'Глен Эллин', 44);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (412, 'Blagoveshchensk', 'Благовещенск', 132);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (413, 'Baltimore', 'Балтимор', 133);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (414, 'Petrozavodsk', 'Петрозаводск', 134);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (415, 'Douglasville', 'Дугласвилл', 15);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (416, 'Modesto', 'Модесто', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (417, "P\'yatyhory", 'Пятигоры', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (418, 'Hnidyn', 'Гнедин', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (419, 'Korosten', 'Коростень', 74);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (420, 'Chabel', 'Чабель', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (421, 'Taraz', 'Тараз', 135);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (422, 'Holmview', 'Холмвью', 136);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (423, 'Shumsk', 'Шумск', 10);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (424, 'Ypsilanti', 'Ипсиланти', 137);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (425, 'Kazanka', 'Казанка', 41);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (426, 'Ploske', 'Плоское', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (427, 'Krasnokutsk', 'Краснокутск', 77);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (428, 'Zarichchya', 'Заречье', 19);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (429, 'Kirkland', 'Керкленд', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (430, 'Port Charlotte', 'Порт-Шарлотт', 23);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (431, 'Lepiel', 'Лепель', 100);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (432, 'Middleburg Heights', 'Миддлбург-Хайтс', 22);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (433, 'Kobeliaky', 'Кобеляки', 93);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (434, 'Kansk', 'Канск', 56);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (435, 'Ruska Polyana', 'Русская Поляна', 27);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (436, 'Kaliningrad', 'Калининград', 138);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (437, 'Veliky Novgorod', 'Великий Новгород', 139);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (438, 'Berezivka', 'Березовка', 28);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (439, 'Vynohradiv', 'Виноградов', 87);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (440, 'Novokuznetsk', 'Новокузнецк', 67);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (441, 'Angarsk', 'Ангарск', 95);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (442, 'Lexington', 'Лексингтон', 117);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (443, 'Warminster', 'Варминстер', 31);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (444, 'Loganville', 'Логанвилл', 15);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (445, 'Phoenix', 'Финикс', 140);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (446, 'Ust-Labinsk', 'Усть-Лабинск', 51);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (447, 'Lepesy Bolshie', 'Большие Лепесы', 30);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (448, 'Fastiv', 'Фастов', 17);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (449, 'Shevchenkove', 'Шевченково', 28);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (450, "Il\'nytsya", 'Ильница', 87);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (451, 'Alicante', 'Аликанте', 141);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (452, 'Guardamar del Segura', 'Гуардамар-дель-Сегура', 141);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (453, 'Sarata', 'Сарата', 28);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (454, 'Spokane Valley', 'Спокан Вэлли', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (455, 'Kirchlengern', 'Кирхленгерн', 71);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (456, 'Druzhnyy', 'Дружный', 7);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (457, 'Thornton', 'Торнтон', 81);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (458, 'Vovkovyi', 'Волковыи', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (459, 'Sarasota', 'Сарасота', 23);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (460, 'Zhovkva', 'Жовква', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (461, 'Ozero', 'Озеро', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (462, 'Triskyni', 'Трискини', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (463, 'Oleksandriia', 'Александрия', 103);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (464, 'Kolodenka', 'Колоденка', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (465, 'Ostrozhets', 'Острожец', 16);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (466, 'Sedlyshche', 'Седлище', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (467, 'Mountlake Terrace', 'Маунтлейк-Террас', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (468, 'St. Augustine', 'Сент-Огастин', 23);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (469, 'Velyki Komyaty', 'Великие Комяты', 87);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (470, 'Kennewick', 'Кенневик', 12);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (471, 'Edmonton', 'Эдмонтон', 142);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (472, 'Fontanka', 'Фонтанка', 28);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (473, 'Santa Barbara', 'Санта-Барбара', 8);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (474, 'Karpylivka', 'Карпиловка', 59);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (475, 'Korsuntsi', 'Корсунцы', 28);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (476, 'Sokal', 'Сокаль', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (477, 'Greer', 'Грир', 78);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (478, 'Zabki', 'Зомбки', 86);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (479, 'Tatarbunary', 'Татарбунари', 28);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (480, 'Stuttgart', 'Штутгарт', 29);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (481, 'Drohobych', 'Дрогобыч', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (482, 'Maykop', 'Майкоп', 143);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (483, 'Pustomyty', 'Пустомыты', 43);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (484, 'Indian Trail', 'Индиан Трейл', 42);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (485, 'Baki', 'Баку', 144);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (486, 'Mynai', 'Минай', 19);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (487, 'Mynai', 'Минай', 87);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (488, 'Dovzhok', 'Довжок', 84);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (489, 'Hannusivka', 'Ганнусовка', 19);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (490, 'Neryungri', 'Нерюнгри', 145);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (491, 'Oshawa', 'Ошава', 33);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (492, 'Koziatyn', 'Казатин', 18);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (493, 'Novorossiysk', 'Новороссийск', 51);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (494, 'Karaganda', 'Караганда', 97);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (495, 'Midland', 'Мидленд', 42);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (496, 'Synelnykove', 'Синельниково', 37);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (497, 'Colorado Springs', 'Колорадо-Спрингс', 81);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (498, 'Aston', 'Астон', 31);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (499, 'Nakhabino', 'Нахабино', 36);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (500, 'Adelaide', 'Аделаида', 146);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (501, 'Maladzyechna', 'Молодечно', 7);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (502, 'San Antonio', 'Сан-Антонио', 127);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (503, 'Dolyna', 'Долина', 19);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (504, 'Bielefeld', 'Билефельд', 71);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (505, 'Torun', 'Торунь', 147);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (506, 'Orenburg', 'Оренбург', 148);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (507, 'Sioux Falls', 'Су-Фолс', 149);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (508, 'Fürth', 'Фюрт', 150);
INSERT INTO `cities` (`id`, `name_en`, `name_ru`, `state_id`) VALUES (509, 'Trostianets', 'Тростянец', 104);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS cities;
-- +goose StatementEnd
